Split user data into its own component
HristovCodes/Events-Board pull request #2
Opened 2020-10-25 21:50 UTC by Bozhidar-A

2020-10-26 06:31 UTC, HristovCodes requested changes
After applying the changes in the review comment on the issue and I'll merge with master.

2020-10-26 06:31 UTC, HristovCodes commented on src/components/UserData/style.scss
> +  font-size: 12px;
Default size is 16 for p's.

2020-10-26 06:31 UTC, HristovCodes commented on src/components/UserData/index.tsx
> +export default function UserData({userData} : UserDataProps) {
Profile or UserProfile would be a better name for the component. UserData is what it shows, data, but the component itself is a profile viewer.

2020-10-26 06:31 UTC, HristovCodes commented on src/components/SideBar/index.tsx
> +  userData: any;
only pass userData.displayName

2020-10-26 06:31 UTC, HristovCodes commented on src/components/SideBar/index.tsx
> +      <UserData userData={userData}></UserData>
Here render a div consisting of an img (for later use for profile pic) and a p for the name.
No need to render <UserData> here.

2020-10-26 06:31 UTC, HristovCodes commented on src/components/Home/index.tsx
>            <Switch>
Inside of the switch make a new ```<Route>``` with the correct to="" property and inside of the switch add the profile component.

2020-10-27 16:15 UTC, Bozhidar-A commented
Managed to implement the requested changes. CSS caused a few bugs so I decided to commit the components in a functional, but unstyled state.

2020-10-27 16:57 UTC, HristovCodes requested changes
Really good. Only small changes are needed to be made. We can merge after this.

2020-10-27 16:57 UTC, HristovCodes commented on src/components/ChangeProfileData/index.tsx
> +export default function SubmitEvent({
99.99% sure this shouldn't be called SubmitEvent

2020-10-27 16:57 UTC, HristovCodes commented on src/components/ChangeProfileData/index.tsx
> +  //funcs and bool stopping invalid urls from being given
This exact thing could be made with state like so:
``` ReactJS
const [validPicURL, setValidity] = useState(false);
```
So 10 lines down to 1 and better readability.

2020-10-27 16:57 UTC, HristovCodes commented on src/components/ChangeProfileData/index.tsx
> +      if(password==confirmPassword)//password and confirm_password fields have the same value
=== always

2020-10-27 16:57 UTC, HristovCodes commented on src/components/ChangeProfileData/index.tsx
> +        <input
stupoed bot i spit on u

2020-10-27 16:57 UTC, HristovCodes commented on src/components/ChangeProfileData/index.tsx
> +      <a className="btnmain" onClick={updateEmail}>
Make this a button with type="button". Does same thing but it's accessible. Only use <a> if you have an href specified.

2020-10-27 16:57 UTC, HristovCodes commented on src/components/ChangeProfileData/index.tsx
> +  if(varToChange === "Photo")//check if photo and prep form
It's literally 3 elements why aren't they rendered all the time with the rest of the profile (same goes for email update form)? I like this way of doing it but I'm curious as to why you think this is better.

2020-10-27 16:57 UTC, HristovCodes commented on src/components/ChangeProfileData/index.tsx
> +}
Good stuff.

2020-10-27 16:57 UTC, HristovCodes commented on src/components/Profile/index.tsx
> +export default function SubmitEvent({
Same thing as in ChangeProfileData

2020-10-27 16:57 UTC, HristovCodes commented on src/components/Profile/index.tsx
> +import { Link, Router, useHistory } from "react-router-dom";
You're not using Router, you can remove it.

2020-10-27 16:57 UTC, HristovCodes commented on src/components/Profile/index.tsx
> +import Firebase from "../../firebase";
You are not using FB, you can remove it.

2020-10-27 16:57 UTC, HristovCodes commented on src/components/SideBar/index.tsx
> +  profileName: any;
Good no need to pass everything if only the name is needed.
Also bad because if you look at the figma board we also need to show the pfp.

2020-10-27 16:57 UTC, HristovCodes commented on src/components/SubmitEvent/index.tsx
> +import { Link, Router, useHistory } from "react-router-dom";
????

2020-10-27 16:57 UTC, HristovCodes commented on src/components/SubmitEvent/index.tsx
> +  //alert(window.location.search);
???

2020-10-27 16:57 UTC, HristovCodes commented on src/components/SideBar/index.tsx
> +            {profileName}
Smart. Instead of profile it will show the name I like this.

2020-10-27 17:44 UTC, Bozhidar-A commented on src/components/ChangeProfileData/index.tsx
> +  if(varToChange === "Photo")//check if photo and prep form
Every website I have ever been to has had a dedicated page to updating your email and password, also I think Profile looks better when it's less cluttered.

2020-10-27 19:31 UTC, HristovCodes approved these changes
Good stuff. Merging.

2020-10-27 19:31 UTC, merged